name: App repo Trigger
on: 
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  call-central-workflow:
    uses: Sudo-Balaji/loya-central-pipelines/.github/workflows/basic-ci.yaml@master
    # THE MAGIC KEYWORD: 'with' is used to pass inputs to the central workflow.
    with:
      app_name: "TestApp"
      
    secrets: inherit
      
      # If we need only any specific secrets follo as per below :-
      #
      # JFROG_TOKEN: ${{ secrets.MY_APP_JFROG_PASSWORD }}
      # AZURE_CREDENTIALS: ${{ secrets.MY_APP_AZURE_SPN }}











